# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyzil/zilliqa/proto/messages.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"pyzil/zilliqa/proto/messages.proto\x12\x0eZilliqaMessage\"\x19\n\tByteArray\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c\"\x81\x02\n\x18ProtoTransactionCoreInfo\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\r\n\x05nonce\x18\x02 \x01(\x04\x12\x0e\n\x06toaddr\x18\x03 \x01(\x0c\x12/\n\x0csenderpubkey\x18\x04 \x01(\x0b\x32\x19.ZilliqaMessage.ByteArray\x12)\n\x06\x61mount\x18\x05 \x01(\x0b\x32\x19.ZilliqaMessage.ByteArray\x12+\n\x08gasprice\x18\x06 \x01(\x0b\x32\x19.ZilliqaMessage.ByteArray\x12\x10\n\x08gaslimit\x18\x07 \x01(\x04\x12\x0c\n\x04\x63ode\x18\x08 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\t \x01(\x0c\"\x88\x01\n\x10ProtoTransaction\x12\x0e\n\x06tranid\x18\x01 \x01(\x0c\x12\x36\n\x04info\x18\x02 \x01(\x0b\x32(.ZilliqaMessage.ProtoTransactionCoreInfo\x12,\n\tsignature\x18\x03 \x01(\x0b\x32\x19.ZilliqaMessage.ByteArray\":\n\x17ProtoTransactionReceipt\x12\x0f\n\x07receipt\x18\x01 \x01(\x0c\x12\x0e\n\x06\x63umgas\x18\x02 \x01(\x04\"\x8e\x01\n\x1bProtoTransactionWithReceipt\x12\x35\n\x0btransaction\x18\x01 \x01(\x0b\x32 .ZilliqaMessage.ProtoTransaction\x12\x38\n\x07receipt\x18\x02 \x01(\x0b\x32\'.ZilliqaMessage.ProtoTransactionReceipt')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pyzil.zilliqa.proto.messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BYTEARRAY']._serialized_start=54
  _globals['_BYTEARRAY']._serialized_end=79
  _globals['_PROTOTRANSACTIONCOREINFO']._serialized_start=82
  _globals['_PROTOTRANSACTIONCOREINFO']._serialized_end=339
  _globals['_PROTOTRANSACTION']._serialized_start=342
  _globals['_PROTOTRANSACTION']._serialized_end=478
  _globals['_PROTOTRANSACTIONRECEIPT']._serialized_start=480
  _globals['_PROTOTRANSACTIONRECEIPT']._serialized_end=538
  _globals['_PROTOTRANSACTIONWITHRECEIPT']._serialized_start=541
  _globals['_PROTOTRANSACTIONWITHRECEIPT']._serialized_end=683
# @@protoc_insertion_point(module_scope)
